#pragma once

#include <stdint.h>
#include "esp_err.h"

/**
 * Display Hardware Abstraction Layer
 * Exposes an Adafruit GFX style API to compile code generated by Blockly.
 */
class BotDisplay {
public:
    BotDisplay();

    esp_err_t init();
    
    // Core drawing
    void fillScreen(uint16_t color);
    void setRotation(uint8_t r);
    
    // Text rendering
    void setCursor(int16_t x, int16_t y);
    void setTextColor(uint16_t color);
    void setTextSize(uint8_t size);
    void print(const char* text);
    
    // Geometry rendering
    void drawLine(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color);
    void drawRect(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color);
    void fillRect(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color);
    void drawCircle(int16_t x0, int16_t y0, int16_t r, uint16_t color);
    void fillCircle(int16_t x0, int16_t y0, int16_t r, uint16_t color);
};

// Global display instance accessed by Blockly user_logic
extern BotDisplay display;
