#ifndef USER_LOGIC_H
#define USER_LOGIC_H

// ============================================================
// This file is auto-generated by BotBuilder Desktop App.
// DO NOT EDIT MANUALLY — your changes will be overwritten.
//
// Available functions & objects:
//   setMotors(leftSpeed, rightSpeed)  — range: -255 to 255
//   delay(ms)                         — pause in milliseconds
//   sensors.readAll()                 — read all IR sensors
//   sensors.getValue(n)               — get sensor n (0-5)
//   robot.stop()                      — stop both motors
//   linePID.compute(setpoint, input)  — PID output
//   linePID.reset()                   — reset PID state
//   Config::LINE_BLACK_THRESHOLD      — IR threshold constant
//   Config::LINE_WEIGHTS[n]           — sensor weight array
// ============================================================

void run_user_sequence() {
  // Your Blockly program will appear here when you compile.
}

#endif